routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// Register Twill routes here eg.
// Route::module('posts');

if (config('twill.enabled.users-management')) {
    Route::module('users', ['except' => ['sort', 'feature']]);
    Route::module('roles', ['except' => ['sort', 'feature']]);
    Route::get('/upload', 'UploadUserController@usersUpload')->name('usersUpload');
    Route::post('/upload','UploadUserController@uploadStore')->name('upload.store');

}

Route::group(['prefix' => 'content'], function(){
    Route::module('pages');
    Route::module('events');
    Route::module('testimonials');
    Route::module('clients');
    Route::group(['prefix' => 'menuses'], function () {
		Route::module('menuses');
        Route::module('menuTypes');
    });
    Route::module('menuses');
    Route::module('socialmedia');
    Route::module('projecttopics');
    Route::module('footerTexts');
});
Route::module('jobRoles');
Route::module('branches');
Route::module('sessions');
Route::module('courseCategories');



Route::group(['prefix' => 'resources'], function(){

    Route::module('resources');
    Route::module('resourceTypes');
    Route::module('resourceThemes');
    Route::module('policies');

});

Route::group(['prefix' => 'groups'], function(){
    Route::module('groups');
    Route::module('groupFormats');

});
Route::group(['prefix' => 'reports'], function(){
	Route::group(['prefix' => 'graph'], function () {
        Route::name('graph.dashboard')->get('dashboard','CourseCompletionController@dashboard');
        Route::name('graph.eresults')->get('eresults','CourseCompletionController@eresults');
        Route::name('graph.cresults')->get('cresults','CourseCompletionController@cresults');
        
        Route::name('graph.yearlyEResults')->get('yearlyEResults','CourseCompletionController@yearlyEResults');
        Route::name('graph.yearlyCRresults')->get('yearlyCRresults','CourseCompletionController@yearlyCRresults');
    });
    Route::group(['prefix' => 'branch'], function () {
        Route::name('branch.completion')->any('branchCompletion','CourseCompletionController@branchCompletion');

    });
Route::module('courseCompletions');
Route::module('courseReflections');
Route::module('userLicenses');

});

Route::group(['prefix' => 'evaluation'], function(){
    Route::module('userEvaluations');
    Route::module('evaluationOptions');
    Route::module('evaluations');
});

Route::group(['prefix' => 'messages'], function(){
    Route::module('generalMessages');
    Route::module('platformMessages');
});

 Route::get('/courses', 'CoursesController@index')->name('courses.index');
 Route::get('/courses/create', 'CoursesController@create')->name('courses.create');
 Route::post('/courses','CoursesController@store')->name('courses.store');
 Route::get('/courses/{course}/edit', 'CoursesController@edit')->name('courses.edit');
 Route::post('/courses/bulk-destroy','CoursesController@bulkDestroy')->name('courses.bulk-destroy');
 Route::post('/courses/{course}','CoursesController@update')->name('courses.update');
 Route::post('/courses/{course}/delete', 'CoursesController@destroy')->name('courses.destroy');



Route::get('/sessionmeetings','SessionMeetingsController@index')->name('sessionmeetings.index');
Route::get('/sessionmeetings/create','SessionMeetingsController@create')->name('sessionmeetings.create');
Route::post('/sessionmeetings','SessionMeetingsController@store')->name('sessionmeetings.store');
Route::get('/sessionmeetings/{sessionMeeting}/edit','SessionMeetingsController@edit')->name('sessionmeetings.edit');
Route::post('/sessionmeetings/bulk-destroy','SessionMeetingsController@bulkDestroy')->name('sessionmeetings.bulk-destroy');
Route::post('/sessionmeetings/{sessionMeeting}','SessionMeetingsController@update')->name('sessionmeetings.update');
Route::delete('/sessionmeetings/{sessionMeeting}','SessionMeetingsController@destroy')->name('sessionmeetings.destroy');


Route::get('/upload/download', 'UploadUserController@downloadExcel')->name('downloadExcel');

Route::post('courseCompletion/export', 'CourseCompletionController@export')->name('courseCompletion.export');
Route::post('courseReflection/export', 'CourseReflectionController@export')->name('courseReflection.export');
Route::get('userLicenses/export', 'UserLicenseController@export')->name('userLicenses.export');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\SessionController;
use App\Http\Controllers\Admin\SessionResourceController;
use App\Http\Controllers\Front\PageController;
use App\Http\Controllers\Front\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Front\CourseController;
use App\Http\Controllers\Front\UserLicenseController;
use App\Http\Controllers\Front\CommentController;
use App\Http\Controllers\Front\BlogCommentController;
use App\Http\Controllers\Front\GroupController;
use App\Http\Controllers\Front\ConnectController;
use App\Http\Controllers\Front\UserActivityReactionsController;
use App\Http\Controllers\Front\UserMessagesController;
use App\Http\Controllers\Front\ForumController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Front\NotificationsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/', [PageController::class, 'index'])->name('home');

Route::post('user/create', [UserController::class, 'create'])->name('user.create');
Route::get('/user/verify', [UserController::class, 'verifyForm'])->name('user.verify');
Route::post('/user/verification', [UserController::class, 'verify'])->name('user.verification');
Route::post('/user/login', [LoginController::class, 'login'])->name('user.login');
Route::post('/general_messages', [PageController::class, 'contactStore'])->name('general_messages.store');
Route::get('/password/verify', [ForgotPasswordController::class, 'verifyForm'])->name('password.verify');
Route::post('/password/verification', [ForgotPasswordController::class, 'verify'])->name('password.verification');

Route::get('/user/resend', [UserController::class, 'resendCode'])->name('resend.code');
Route::post('/user/resend', [UserController::class, 'resendStore'])->name('resend.store');

Auth::routes(['verify' => true]);


Route::any('/{key}',[PageController::class, 'pages'])->name('pages');

Route::group(['prefix'=>'profile', 'middleware'=>['auth', 'verified']], function () {
Route::get('/session-details/{id}', [PageController::class, 'sessionDetail'])->name('session.details');
Route::get('/policy-details/{id}', [PageController::class, 'policyDetail'])->name('policy.details');

Route::get('/course/detail/{key}', [CourseController::class, 'detail'])->name('course.detail');
Route::get('/courses/enroll/{id}', [CourseController::class, 'enroll'])->name('course.enroll');
Route::any('/myProfile', [UserLicenseController::class, 'profile'])->name('profile.courses');



Route::any('/resources', [PageController::class, 'resources'])->name('resources');
Route::get('/resource-details/{id}', [PageController::class, 'resourceDetails'])->name('resource.details');
Route::post('save-likedislike', [CommentController::class,'save_likedislike'])->name('save_likedislike');




    Route::any('/achievements', [UserLicenseController::class, 'achievements'])->name('profile.achievements');
    Route::any('/myCommunity', [UserLicenseController::class, 'community'])->name('profile.myCommunity');
    Route::any('/myCommunity/follow/{follow}/{id}/', [UserLicenseController::class, 'myFollow'])->name('profile.myFollow');
    Route::any('/myCommunity/followRequests/', [UserLicenseController::class, 'myFollowRequests'])->name('profile.myFollowRequests');
    Route::any('/myCommunity/accept/{id}/{follow}', [UserLicenseController::class, 'myFollowAccept'])->name('profile.myFollowAccept');


    Route::any('/trainingFeed', [UserLicenseController::class, 'trainingFeed'])->name('profile.trainingFeed');
    Route::any('/like/{follow}/{id}/', [UserLicenseController::class, 'myLike'])->name('profile.myLike');
    Route::post('/comment', [UserLicenseController::class, 'myComment'])->name('profile.myComment');
    Route::get('/comments/{follow}/{course}/', [UserLicenseController::class, 'myComments'])->name('profile.myComments');
    Route::get('/subCommentCount/{follow}/{course}/{id}/', [UserLicenseController::class, 'subCommentCount'])->name('profile.subCommentCount');
    Route::get('/subComment/{follow}/{course}/{id}/', [UserLicenseController::class, 'subComment'])->name('profile.subComment');
    Route::post('/course/evaluate/store', [UserLicenseController::class, 'Evaluationstore'])->name('course.evaluate.store');
    Route::any('/course/evaluate/{courseid}', [UserLicenseController::class, 'evaluate'])->name('course.evaluate');
    Route::any('/course/certificate/{id}', [UserLicenseController::class, 'certificate'])->name('course.certificate');
    Route::any('/edit', [UserController::class, 'profile'])->name('profile.edit');
    Route::any('/password/set', [UserController::class, 'password'])->name('profile.password.set');
    Route::any('/ppic/change', [UserController::class, 'picture'])->name('profile.ppic.change');

    Route::any('/course/certificate/{id}', [UserLicenseController::class, 'certificate'])->name('course.certificate');
    Route::any('/myProgress', [UserLicenseController::class, 'myProgress'])->name('profile.myProgress');


    Route::any('/connect', [ConnectController::class, 'activity'])->name('connect.activity');
    Route::post('/connect/create', [ConnectController::class, 'createAcivity'])->name('activity.create');
    Route::post('/connect/delete/{userActivity}', [ConnectController::class, 'deleteAcivity'])->name('activity.delete');
    Route::post('/connect/reply/create/{userActivity}', [ConnectController::class, 'createAcivityReply'])->name('reply.create');
    Route::post('/connect/reactions/{activityId}', [UserActivityReactionsController::class, 'reaction'])->name('reactions.create');
    Route::post('/connect/reply/reply/create/{userActivity}/{userActivityReply}', [UserActivityReactionsController::class, 'replyOnActionReply'])->name('reply.reply.create');
    Route::post('/connect/reply/reacttions/create/{userActivityId}/{userActivityReplyId}', [UserActivityReactionsController::class, 'reactOnReply'])->name('react.reply.create');

    Route::post('/messages/create', [UserMessagesController::class, 'sentMessage'])->name('message.create');
    Route::get('/messages/all', [UserMessagesController::class, 'index'])->name('message.index');
    Route::post('/messages/users/search/{name?}', [UserMessagesController::class, 'searchForUser'])->name('message.search');
    Route::get('/messages/chat/{user}', [UserMessagesController::class, 'getUserChat'])->name('message.chat');

    Route::any('/connect-profile/{id}', [ConnectController::class, 'profile'])->name('connect.profile');
    Route::any('/connect-profile', [ConnectController::class, 'profile'])->name('connect.my_profile');


    
    Route::any('/forum', [ForumController::class, 'index'])->name('connect.forum');
    Route::any('/connect/forum/topic', [ForumController::class, 'storeTopic'])->name('forum.topic.store');
    Route::any('/connect/forum/create', [ForumController::class, 'store'])->name('forum.store');

    Route::any('/connect/forum/follow/{id}', [ForumController::class, 'follow'])->name('forum.follow');
    Route::any('/forum/{id}', [ForumController::class, 'details'])->name('forum.details');
    Route::post('/connect/forum/reply/create/{userActivity}', [ForumController::class, 'createAcivityReply'])->name('forum.reply.create');
    Route::post('/connect/forum/reply/edit/{userActivity}', [ForumController::class, 'updateReply'])->name('connect.reply.update');
    Route::post('/connect/forum/reply/delete/{userActivity}', [ForumController::class, 'deleteReply'])->name('connect.reply.delete');
    Route::post('/connect/forum/reactions/{activityId}', [ForumController::class, 'reaction'])->name('forum.reactions.create');
    Route::post('/connect/forum/reply/reply/create/{userActivity}/{userActivityReply}', [ForumController::class, 'replyOnActionReply'])->name('forum.reply.reply.create');
    Route::post('/connect/forum/reply/reply/edit/{userActivity}', [ForumController::class, 'updateReplyReply'])->name('connect.reply.reply.update');
    Route::post('/connect/forum/reply/reply/delete/{userActivity}', [ForumController::class, 'deleteReplyReply'])->name('connect.reply.reply.delete');
    Route::post('/connect/forum/reply/reacttions/create/{userActivityId}/{userActivityReplyId}', [ForumController::class, 'reactOnReply'])->name('forum.react.reply.create');

    Route::any('/connect/forum/getforum/{id}', [ForumController::class, 'getForums'])->name('get.forums');
    Route::any('/connect/forum/getStatus/{id}/{user}', [ForumController::class, 'getStatus'])->name('get.status');

    Route::any('/groups', [GroupController::class, 'list'])->name('groups');
    Route::get('/group/activate/{id}/{key}', [GroupController::class, 'activate'])->name('group.activate');
    Route::get('/group/decline/{id}/{key}', [GroupController::class, 'decline'])->name('group.decline');
    Route::get('/group/request/{id}/{key}', [GroupController::class, 'request'])->name('group.request');
     
    Route::get('/groups/details/{id}/{key}', [GroupController::class, 'details'])->name('group.details');
    Route::any('/myGroup/followRequests/{id}', [GroupController::class, 'myFollowRequests'])->name('group.profile.myFollowRequests');
    Route::any('/myGroup/accept/{id}/{follow}', [GroupController::class, 'myFollowAccept'])->name('group.profile.myFollowAccept');

    Route::get('/group/create', [GroupController::class, 'form'])->name('group.form');
    Route::post('/group/store', [GroupController::class, 'store'])->name('group.store');
    Route::get('/group/edit/{id}', [GroupController::class, 'edit'])->name('group.edit');

app/Models/Branch.php
<?php

namespace App\Models;

use A17\Twill\Models\Behaviors\HasBlocks;
use A17\Twill\Models\Behaviors\HasTranslation;
use A17\Twill\Models\Behaviors\HasSlug;
use A17\Twill\Models\Behaviors\HasMedias;
use A17\Twill\Models\Behaviors\HasFiles;
use A17\Twill\Models\Behaviors\HasRevisions;
use A17\Twill\Models\Behaviors\HasPosition;
use A17\Twill\Models\Behaviors\Sortable;
use A17\Twill\Models\Model;
use Auth;

class Branch extends Model implements Sortable
{
    use HasBlocks, HasTranslation, HasSlug, HasMedias, HasFiles, HasRevisions, HasPosition;

    protected $fillable = [
        'published',
        'title',
        'description',
        'position',
    ];
    
    public $translatedAttributes = [
        'title',
        'description',
        'active',
    ];
    
    public $slugAttributes = [
        'title',
    ];
    
    public $mediasParams = [
        'cover' => [
            'default' => [
                [
                    'name' => 'default',
                    'ratio' => 16 / 9,
                ],
            ],
            'mobile' => [
                [
                    'name' => 'mobile',
                    'ratio' => 1,
                ],
            ],
            'flexible' => [
                [
                    'name' => 'free',
                    'ratio' => 0,
                ],
                [
                    'name' => 'landscape',
                    'ratio' => 16 / 9,
                ],
                [
                    'name' => 'portrait',
                    'ratio' => 3 / 5,
                ],
            ],
        ],
    ];


   public function users(){

    return $this->hasMany(User::class);

   }


   public function completions(){

    return $this->hasMany(CourseCompletion::class);

   }

   public function  getRegisteredAttribute(){
    $users = array();

    foreach($this->users as $user){
       
        $users[] = $user->id;
    }

    return count($users);
   
   }



   public function  getCompletedAttribute(){
    
    $compulsories = array();
    $complete = array();
    $total = array();

    $users = $this->users;
    

    foreach( $users as $key => $user){
        $compulsory = JobroleCourse::where('job_role_id','=',$user->job_role_id)->get();
        $completed = CourseCompletion::where('user_id','=',$user->id)->get();
       
    
        if(count($completed) > 0){
            foreach($compulsory as $comp){
                $compulsories[] = $comp->course_id;
               }
            foreach($completed as $compl){
                 $complete[] = $compl->course_id;
        
            }

             if(count($compulsories) != count($complete)){
                unset($users[$key]);

             }else{

                $total[] += 1;
             }
                
        }else{

            unset($users[$key]);
        }
  
       
    }

 
    
    return count($total);
   
   }

}

resources/views/admin/courseCompletions/branchCompletion.blade.php
@extends('layouts.admin.reports')
@push('extra_css')
	<link href="{{ asset('/css/reports.css') }}" rel="stylesheet">
	<style>
		.report_visual {
			margin-bottom: 30px;
		}
        .container {
            width: 100% !important;
        }

	</style>

	<meta name="csrf-token" content="{{ csrf_token() }}">
@endpush
@section('customPageContent')
<div class="listing">

	<div id="container-fluid">

        <div class="row">

            <div class="col-12">
                <form action="{{ route('admin.branch.completion') }}" method="POST" class="homeForm">
                    @csrf
                    <div class="row justify-content-center">

                        @error('category')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror

                        <div class="col-9 no-padding-right ">
                            <div class="row">

                                <div class="col-2 mt-4 mb-4 ">
                                    <label class="filter_by" style="color:#000"> Filter branches by</label>
                                </div>
                                {{-- <div class="col-4">
                                    <select name="country" id="" class="form-control mt-4 mb-4 ">
                                        <option value=''>Select Country</option>
                                        @foreach (App\Models\Country::published()->orderByTranslation('title')->get() as $theme)
                                            <option value="{{ $theme->id }}"> {{ $theme->title }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div> --}}
                                <div class="col-5">

                                    <input type="text" placeholder="Free text search ... eg branch name" class="form-control mt-4 mb-4 " name="search">

                                </div>

                            </div>

                        </div>

                        <div class="col-3 ">
                            <button type="submit"
                                class="mt-4 mb-4" style="
                                margin-top: 40px;
                                margin-left: 20px;
                                color: rgb(255, 255, 255);
                                background: #1a8f36;
                                border:1px solid #1a8f36;
                                padding: 10px;
                                text-decoration: none;">Search</button>

                            <button type="reset" class=" mt-4 mb-4" style="
                            margin-top: 40px;
                            margin-left: 20px;
                            color: rgb(255, 255, 255);
                            background: rgb(255, 0, 0);
                            border:1px solid rgb(255, 0, 0);
                            padding: 10px;
                            text-decoration: none;"
                                onClick="window.location.href=window.location.href">Reset</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
        <div class="row">
            <div class="col">
			  <table class="table" style="text-align: center">
                <thead></thead>
                <tr class="tablehead">
                    <th> #</th>
                    <th> Branch</th>
                    <th> Number of Registrations</th>
                    <th> Number of Completions</th>
                </tr>
            </thead>
                <tbody>
                    @php $i = 1; @endphp
                    @foreach($branches as $branch)
                    <tr class="tablerow">
                    <td class="tablecell">{{ $i++}}</td>
                    <td class="tablecell">{{ $branch->title }}</td>
                    <td class="tablecell">{{ $branch->registered }}</td>
                    <td class="tablecell">{{ $branch->completed }}</td>
                </tr>
                  @endforeach
                </tbody>
              </table>

              {!! $branches->links() !!}
			</div>

    </div>

</div>
</div>
@stop
@push('extra_js')
<script src="{{ twillAsset('main-free.js') }}" crossorigin></script>

@endpush

resources/views/admin/courseCompletions/form.blade.php
@extends('twill::layouts.form')

@section('contentFields')
    @formField('input', [
        'name' => 'description',
        'label' => 'Description',
        'maxlength' => 100
    ])
@stop

resources/views/admin/courseCompletions/subsidiaryCompletion.blade.php
@extends('layouts.admin.reports')
@push('extra_css')
	<link href="{{ asset('/css/reports.css') }}" rel="stylesheet">
	<style>
		.report_visual {
			margin-bottom: 30px;
		}
        .container {
            width: 100% !important;
        }

	</style>

	<meta name="csrf-token" content="{{ csrf_token() }}">
@endpush
@section('customPageContent')
<div class="listing">

	<div id="container-fluid">

        <div class="row">

            <div class="col-12">
                <form action="{{ route('admin.branch.completion') }}" method="POST" class="homeForm">
                    @csrf
                    <div class="row justify-content-center">

                        @error('category')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror

                        <div class="col-9 no-padding-right ">
                            <div class="row">

                                <div class="col-2 mt-4 mb-4 ">
                                    <label class="filter_by" style="color:#000"> Filter Subsidiary by</label>
                                </div>
                                {{-- <div class="col-4">
                                    <select name="country" id="" class="form-control mt-4 mb-4 ">
                                        <option value=''>Select Country</option>
                                        @foreach (App\Models\Country::published()->orderByTranslation('title')->get() as $theme)
                                            <option value="{{ $theme->id }}"> {{ $theme->title }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div> --}}
                                <div class="col-5">

                                    <input type="text" placeholder="Free text search ... eg Subsidiary name" class="form-control mt-4 mb-4 " name="search">

                                </div>

                            </div>

                        </div>

                        <div class="col-3 ">
                            <button type="submit"
                                class="mt-4 mb-4" style="
                                margin-top: 40px;
                                margin-left: 20px;
                                color: rgb(255, 255, 255);
                                background: #1a8f36;
                                border:1px solid #1a8f36;
                                padding: 10px;
                                text-decoration: none;">Search</button>

                            <button type="reset" class=" mt-4 mb-4" style="
                            margin-top: 40px;
                            margin-left: 20px;
                            color: rgb(255, 255, 255);
                            background: rgb(255, 0, 0);
                            border:1px solid rgb(255, 0, 0);
                            padding: 10px;
                            text-decoration: none;"
                                onClick="window.location.href=window.location.href">Reset</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>
        <div class="row">
            <div class="col">
			  <table class="table" style="text-align: center">
                <thead></thead>
                <tr class="tablehead">
                    <th> #</th>
                    <th> Subsidiary Name</th>
                    <th> Number of Registrations</th>
                    <th> Number of Completions</th>
                    <th> Percentage of Completions</th>
                </tr>
            </thead>
                <tbody>
                    @php $i = 1; @endphp
                    @foreach($companies as $company)
                    <tr class="tablerow">
                    <td class="tablecell">{{ $i++}}</td>
                    <td class="tablecell">{{ $company->title }}</td>
                    <td class="tablecell">{{ $company->registered }}</td>
                    <td class="tablecell">{{ $company->completed }}</td>
                    <td class="tablecell">{{ round($company->percentage) }} </td>
                </tr>
                  @endforeach
                </tbody>
              </table>

              {!! $companies->links() !!}
			</div>

    </div>

</div>
</div>
@stop
@push('extra_js')
<script src="{{ twillAsset('main-free.js') }}" crossorigin></script>

@endpush